- name: disable default nginx module
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx 24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: updating config files
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup App prerequisites
  ansible.builtin.include_role:
   name: common
   tasks_from: app-prereq
  
- name: start service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true

 