- name: disable default nginx module
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx 24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.install:
    name: nginx
    state: latest

- name: updating config file
  ansible.builtin.copy:
    source: nginx.conf
    dest: /etc/nginx/nginx.conf

#APP_PREREQ
  
- name: start service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true

 