- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server

- name: restart mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: setup  mysql root passwoqd
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
