- name: Install Golang
  ansible.builtin.dnf:
    name: golang
    state: latest

- name: Setup App prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: download NodeJS depedencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go biult
  args:
    chdir: "{{ app_path }}"


- name: load schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
    when: schema_setup is defined


- name: Seystemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

