- name: maven install and java
  ansible.builtin.dnf:
    name: maven

- name: Setup App prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name:  download dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}-v3.jar
  args:
    chdir: "{{ app_path }}"

- name: load schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
  when: schema_setup is defined


- name: Systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd