- node: Disable NodeJS Default Version
  ansible.builtin.shell: dnf  module disable nodejs -y

- node: enable NodeJS 20 Module
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- node: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Setup App prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- node: download NodeJS depedencies
  ansible.builtin.shell: npm install
  args:
    chdir: "{{ app_path }}"


- name: load schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema


- name: Seystemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

