- name: Load MongoDB Schema
  when: schema_setup == "mongo"
  block:
   - name: copy MongoDB repo File
     ansible.builtin.template:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

   - name: install mongo client
     ansible.builtin.dnf:
      name: mongodb-mongosh
      state: latest

   - name: load master data
     ansible.builtin.shell: mongosh --host mongo.{{ env }} </app/db/{{ item }}.js
     loop: "{{schema_files}}"

- name: load mysql schema
  when: schema_setup ==  "mysql"
  block:
    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: load master data
      ansible.builtin.shell: mysql -h mysql.{{ env }}.devopsb72.online -uroot -pRoboShop@1 < /app/db{{ item }}.sql
      loop: "{{schema_files}}"

